[package]
name = "bytebeat-rs"
version = "0.1.0"
edition = "2024"
description = "Library crate for bytebeat binary"
license = "MIT"

[dependencies]
stacker = "0.1"
ordered-float = "5"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
llvm-sys = { version = "180", features = ["prefer-dynamic"] }
indenter = "0.3"

[dev-dependencies]
rayon = "1"